### ISSUE TITLE
Retrieving meeting changes in a date range returns all stored meeting changes

### ISSUE THREAD

**Issue by heisler98** [bmlt-enabled/BMLTiOSLib#1] opened 2018-12-02 23:16 UTC
Using `BMLTiOSLib.getAllMeetingChanges(fromDate:toDate:)` returns every meeting change stored on the root server, regardless of the arguments provided. I believe I may have identified the bug in `BMLTiOSLibCommunicationHandler.swift`, in the `getAllMeetingChanges(inFromDate:inToDate:inServiceBodyID:inMeetingID:inUserID:inMeetingNode:)` function declaration, on line 473. If the date format string reads `"YYYY-MM-dd"` instead of `"YYYY-MM-DD"`, the date is properly formatted for the query, and returns the changes in the provided range.

**Comment by pjaudiomv** [comment] 2018-12-28 01:35
@LittleGreenViper @BMLTGuy seems to be some merit in this as well `DD` is not a proper date field symbol where as `dd` is 

http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns

this appears her line 473
https://github.com/bmlt-enabled/BMLTiOSLib/blob/d1fb6b09cd96258137a58c9adb4ca5d8637291ba/BMLTiOSLib/Framework%20Project/Classes/BMLTiOSLibCommunicationHandler.swift#L473

and here line 515
https://github.com/bmlt-enabled/BMLTiOSLib/blob/d1fb6b09cd96258137a58c9adb4ca5d8637291ba/BMLTiOSLib/Framework%20Project/Classes/BMLTiOSLibCommunicationHandler.swift#L515

**Comment by LittleGreenViper** [comment] 2018-12-28 01:38
No, that's correct. Remember that this is Apple iOS, not PHP:
https://developer.apple.com/documentation/foundation/dateformatter

**Comment by pjaudiomv** [comment] 2018-12-28 01:40
ah yes gotcha I assumed they would be the same, I guess we know what happens when we do that.

**Comment by LittleGreenViper** [comment] 2018-12-28 01:41
I'm pretty sure that it's fixed.
Are you on the guest list for testing the NA Admin app in TestFlight?

**Comment by pjaudiomv** [comment] 2018-12-28 01:42
yes i am

**Comment by LittleGreenViper** [comment] 2018-12-28 01:42
That was a great guess, by the way. You're pretty good at this stuff.

**Comment by pjaudiomv** [comment] 2018-12-28 01:44
I like fixing problems

**Comment by LittleGreenViper** [comment] 2018-12-28 01:46
Good show. Good skill to have.
In a day or so, you'll get an update notice. Apple needs to vet the new version before it can be tested.

**Comment by pjaudiomv** [comment] 2018-12-28 01:48
ok cool

**Comment by pjaudiomv** [comment] 2018-12-28 01:58
not to be a thorn in the side here but according to this doc https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1
DateFormatter format strings do use Unicode Technical Standard #35 

http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns

where 'DD' would represent day of year and `dd` represent day of month

**Comment by pjaudiomv** [comment] 2018-12-28 02:01
so using that string `YYYY-MM-DD` todays date would be `2018-12-362` 
using  `YYYY-MM-dd` would produce `2018-12-28`

**Comment by LittleGreenViper** [comment] 2018-12-28 02:01
Ooh. I'll look it over. Don't have time for it tonight, but I'll check on it mañana.
Wouldn't be the first time that two different docs disagreed with each other (or I got confused, reading them).

**Comment by pjaudiomv** [comment] 2018-12-28 02:03
yea it certainly can be confusing with dates I just watched this sweet screencast on dates with swift ha
https://nsscreencast.com/episodes/367-dates-and-times

https://nsdateformatter.com/

**Comment by LittleGreenViper** [comment] 2018-12-28 02:05
I do know there's differences between PHP and iOS (It's not Swift -it's the toolbox). I've been burned by that before.

I'll have to look at the context, but it's entirely possible that I use their string to date format reader, and it might be forgiving me my goof.

**Comment by LittleGreenViper** [comment] 2018-12-28 02:06
Also, this seems to be the first time that someone is seriously exercising that code path.

**Comment by pjaudiomv** [comment] 2018-12-28 02:12
I also thought that same thing.

**Comment by LittleGreenViper** [comment] 2018-12-28 11:13
Good show. I appreciate the extra eyeballs. This was, indeed, an issue, and it should be corrected in the next release.

**Comment by LittleGreenViper** [comment] 2018-12-28 11:23
I'll ask folks to test this, once Apple vets it (might be a day or so).

The 1.3.2. 2003 version will have the second date fix. The 2002 version has the first, but I plan to make the first release 2003. If Apple beats me to the update, then 2002 may make it first.

**Comment by LittleGreenViper** [comment] 2018-12-28 11:23
BTW: If anyone else wants to be on the TestFlight guest list for these things, let me know, and I'll lift the velvet rope.

**Comment by pjaudiomv** [comment] 2018-12-28 15:25
awesome im really gonna blow your mind now haha I'd say we are good now, but just wanted to give you heads up in any future endeavors. this is from apple dev docs per UTS #35 specs
`A common mistake is to use YYYY. yyyy specifies the calendar year whereas YYYY specifies the year (of “Week of Year”), used in the ISO year-week calendar. In most cases, yyyy and YYYY yield the same number, however they may be different. Typically you should use the calendar year.`

**Comment by pjaudiomv** [comment] 2018-12-28 15:26
good catch @heisler98 send your email on over if you haven't already to join the TestFlight

**Comment by LittleGreenViper** [comment] 2018-12-28 15:48
Good point. I'll switch it to lowercase. I've used uppercase forever. Thanks!

**Comment by LittleGreenViper** [comment] 2018-12-28 15:50
I won't update the release (until later), as it's not worth it for that.

However, I should fix it in the CocoaPod, and that will end up in the final release.

Thanks!

**Comment by pjaudiomv** [comment] 2018-12-28 15:56
yea one of these days ill have to get you to give me a quick tutorial on getting test environment set up. I tried building local but couldnt figure out how ot associate the cocoapod with project

**Comment by LittleGreenViper** [comment] 2018-12-28 16:03
It's a bit of a pain. You need to set up a podfile.

The problem is that you need to set up the podfile to exactly match a version to get a true "snapshot," like you'd need for forensics. However, that kind of devalues CocoaPods.

As you know, I'm a bit of a dependency skeptic. It's not an "old curmudgeon" thing, but I have been watching dependency addiction causing a lot of issues.

Apple is also pretty skeptical.

However, that doesn't matter. Dependencies are here to stay, and they do offer some really major benefits. We have to wait for dependency management to get into shape.

Despite the hype, it isn't a "solved problem" yet, but it's much better than it was a year or so ago.

**Comment by pjaudiomv** [comment] 2018-12-28 16:14
nice thanks that was easy
```
sudo gem install cocoapods
cd NA-Meeting-List-Administrator
pod install
```

bam at least got it to build now :)

**Comment by LittleGreenViper** [comment] 2018-12-28 16:18
Yeah, that'll do it.

CocoaPods and Jazzy are a couple of useful utilities for iOS/MacOS developers. I think they are both Realm projects.

Realm is fairly good with these Ruby utilities.

**Comment by LittleGreenViper** [comment] 2018-12-29 19:48
I am closing this, even though the NA meeting List Admin app is still under test.

BMLTiOSLib is a separate project, and it has been released.

Thanks so much!

**Closed as completed by LittleGreenViper** 2018-12-29 19:48 UTC
Labels: good first issue
